travis:
  secure:
    BINSTAR_TOKEN: iHK2UXYlypV0IsiFOOsH7Q3d3JRRyGM/6TEaZlGIroZHqbFEqpAcbJlhSUh8889ozJ9IZk4CkVEOR5xuhUkdKlVLsd/kh9b4t3c5DdQPMEj7rHJdvG0wkTn/T/RTpqcKLzX5Q61H2AWBmtN7Mf8Slw1XhnBqhcV97o1jhzhrBe87x1ZcvEA7jJJbe9WrYgCiPp3t42I+D2EjOlXrqU1BUZUiQ7/2REoXp/vLjSiGtvWVKTPXEqq3vMO266BeLiY44f94+TwP5rDbIAFjFjV93t0iy4yQ5+qIxETmMxo66tioqJMXwHr6xaJxebtm68UEfsiiiQqzK+i2u6yAqEWXBvehjtPQEC/HANsDyk8qS/VnHg7m9JqRAuP/KTDDnpohN+i3aRgXAFK1dMPsoCEwOrar8rkD2VmCYmlYkbo7lLnoPHaKB2zcQxRM6YrSu8CT0tOgIAnl/uQlLmWHqPyooLT2ONK1JFigUG7/cRS4EE8s8mu1c603EBC1IM5oe/6yPZd/UDCpsQeNm55WhT2IAjiVULcyq7XVjDquyjftq9hPlt1LfzAbV8nlvT9N/Jv3QtAaa0w/CfhCEifi3n1tC+QyOY/5yjRukSRn7b1uHadZ6Cr/97D40OoNUcJgWshQSPaC8O9i0lMMDKMuCSgHvi4GUKjjykpd1AX69xyRUN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
